### ISSUE TITLE
databricks_grants dependency issue 

### ISSUE THREAD

**Issue by louiscsq** [AbhiDatabricks/databricks-uc-quickstart#13]
The grant/main.tf file was complaining that the catalog does not exist when Terraform apply was run for the first time. Rerunning Terraform apply resolved the issue. We probably need to add an explicit dependency if we encounter this issue again.
![image](https://github.com/user-attachments/assets/a468ddc5-a8ab-480d-9a38-9a39dcc447d4)

**Comment by renjil** [comment]
dependency added
