### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by AbhiDatabricks** [AbhiDatabricks/databricks-uc-quickstart#3]
<img width="1507" alt="Screenshot 2024-05-27 at 10 06 32 AM" src="https://github.com/AbhiDatabricks/databricks-uc-quickstart/assets/110456615/81a9721b-3ec3-4749-a467-d0671b75498a">

**Comment by AbhiDatabricks** [comment]
Please update relevant documentation so end user dont see this error

**Comment by renjil** [comment]
Error resolved
