### ISSUE TITLE
AWS Setup dont recognised standard crendetials set in ~/.aws

### ISSUE THREAD

**Issue by AbhiDatabricks** [AbhiDatabricks/databricks-uc-quickstart#7]
If I have setup aws cli and have relevant files in ~/.aws,the setup should not ask for credentials

**Comment by AbhiDatabricks** [comment]
![Uploading Screenshot 2024-07-15 at 10.13.54 AM.png…]()

**Comment by louiscsq** [comment]
@AbhiDatabricks Please review [the fix](https://github.com/AbhiDatabricks/databricks-uc-quickstart/pull/16) and merge.
