### ISSUE TITLE
Create a .tfvars.template for aws

### ISSUE THREAD

**Issue by AbhiDatabricks** [AbhiDatabricks/databricks-uc-quickstart#9]
databricks_account_id = "XX"
databricks_host       = "https://XX.com"
databricks_token      = "XX"

# AWS credentials
aws_access_key = "XX"
aws_secret_key = "XX/2KU3AYaueBzfJQeiXFqhE6"
aws_account_id = "1234567890"

**Comment by louiscsq** [comment]
@AbhiDatabricks please review the [template](https://github.com/AbhiDatabricks/databricks-uc-quickstart/blob/main/aws/template.tfvars.example)

**Comment by renjil** [comment]
Template created
